###
GET {{baseUrl}}/api/users/me
Authorization: {{authorization}}

###
GET {{baseUrl}}/api/tile-collections
Authorization: {{authorization}}

###
GET {{baseUrl}}/api/images?path=./google
Authorization: {{authorization}}
